### ISSUE TITLE
Add example showing how to add tools other than code_interpreter

### ISSUE THREAD

**Issue by psschwei** [i-am-bee/bee-python-sdk#11]
Trying to create an agent using a tool other than the code_interpreter results in an error.

For example, trying to execute the following code:

```python
#! /usr/bin/env python3
import os
import dotenv
from openai import OpenAI

dotenv.load_dotenv()

client = OpenAI(base_url=f'{os.getenv("BEE_API")}/v1', api_key=os.getenv("BEE_API_KEY"))

assistant = client.beta.assistants.create(
    name="Current Affairs Bee",
    model="meta-llama/llama-3-1-70b-instruct",
    tools=[{"type": "weather"}],
    description="Get the current weather",
    instructions="Get the current temperature for the location provided by the user. Return results in Fahrenheit."
)

```

results in the following error

```
Traceback (most recent call last):
  File "/home/paulschw/i-am-bee/bee-hive/bee-hive/./create.py", line 10, in <module>
    assistant = client.beta.assistants.create(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulschw/i-am-bee/bee-hive/venv/lib64/python3.11/site-packages/openai/resources/beta/assistants.py", line 146, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/paulschw/i-am-bee/bee-hive/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 1280, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulschw/i-am-bee/bee-hive/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 957, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/paulschw/i-am-bee/bee-hive/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 1061, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'code': 'invalid_input', 'message': "body/tools/0 must have required property 'user', body/tools/0 must have required property 'function', body/tools/0/type must be equal to constant, body/tools/0/type must be equal to constant, body/tools/0 must have required property 'system', body/tools/0 must match exactly one schema in oneOf"}}
```

As `weather` is one of the tools provided by the bee-stack, I would like an example of how to enable it via the python sdk.

**Comment by psschwei** [comment]
In theory, one could query the list of tools (`tools = client.get('/tools', cast_to=BaseModel)`) and then grab the `json_schema` of the relevant tool, though this seems a little hacky
